- name: install nginx
  hosts: frontend
  become: yes
  tasks: #install nginx
  - name: nginx
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create dir
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense.conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart service
    ansible.builtin.service:
      name: nginx
      state: restarted