- name: MySQL Server 8.0.x
  hosts: Mysql
  become: yes
  vars: 
    passwd: ExpenseApp@1
  tasks: #MySQL Server 8.0.x
    - name: install Mysql libraries
    ansible.builtin.pip:
     name: PyMySQL
     executable: pip3.9

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Collect all info except settings and users by root
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{passwd}}"
      login_host: mysql.dpumedia.site
    register: Mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "Mysql info: {{Mysql_info}}"

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{passwd}}"
    when: "Mysql_info.failed is true"
  