- name: MySQL Server 8.0.x
  hosts: Mysql
  become: yes
  tasks: #MySQL Server 8.0.x
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  